name: my_task_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  location: ^6.0.2
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.2.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0

  management_task_package:
    git:
      url: https://github.com/tiagoserra/24E2_3_package.git
      ref: main
      path: src/management_task_package
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true