// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDomLYibm8hTbVfdp47o1_hWgA_3lOMWmo',
    appId: '1:1019204694515:web:59c1f113fc4a3ca24fe286',
    messagingSenderId: '1019204694515',
    projectId: 'flutter-tasks-27c22',
    authDomain: 'flutter-tasks-27c22.firebaseapp.com',
    databaseURL: 'https://flutter-tasks-27c22-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-tasks-27c22.appspot.com',
    measurementId: 'G-RQRSSE8KN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb5r1CV8LupKT_uTCTIrASgGQbkPhjfhA',
    appId: '1:1019204694515:android:645d28d97115b3ee4fe286',
    messagingSenderId: '1019204694515',
    projectId: 'flutter-tasks-27c22',
    databaseURL: 'https://flutter-tasks-27c22-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-tasks-27c22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvApG4DuDSUm5Zmgm1ZYHI_nLpIBuT0MY',
    appId: '1:1019204694515:ios:5aaea2fdbea94b644fe286',
    messagingSenderId: '1019204694515',
    projectId: 'flutter-tasks-27c22',
    databaseURL: 'https://flutter-tasks-27c22-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-tasks-27c22.appspot.com',
    iosBundleId: 'com.example.myTaskApp',
  );
}
